# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_data', models.DateTimeField(auto_now=True, error_messages={'invalid': '日期格式错误'}, null=True)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('cancelreasion', models.CharField(max_length=100, null=True)),
                ('cashfinish', models.CharField(choices=[(1, '是'), (2, '否')], max_length=10, null=True)),
                ('finishincome', models.CharField(max_length=50, null=True)),
                ('frequency', models.CharField(choices=[(1, '天/次'), (2, '周/次'), (2, '月/次')], max_length=50, null=True)),
                ('income', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(max_length=50, null=True)),
                ('paytime', models.DateTimeField(null=True)),
                ('payreasion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[(1, '猫'), (2, '狗'), (3, '小宠'), (4, '其他')], max_length=10, null=True)),
                ('like', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petposition', models.CharField(choices=[(1, '1号房'), (2, '2号房'), (3, '3号房'), (4, '4号房'), (5, '5号房'), (6, '6号房')], default=1, max_length=50, null=True)),
                ('footposition', models.CharField(choices=[(1, '1号食物柜'), (2, '2号食物柜'), (3, '3号食物柜'), (4, '4号食物柜'), (5, '5号食物柜'), (6, '6号食物柜')], default=1, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=50, null=True)),
                ('adress', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='pethost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_user', to='TestModle.UserInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='ord_pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pet', to='TestModle.Pet'),
        ),
        migrations.AddField(
            model_name='order',
            name='ord_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='TestModle.UserInfo'),
        ),
    ]
