# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='telephone',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
