# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModle', '0002_auto_20180131_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='name',
            new_name='petname',
        ),
    ]
