# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModle', '0004_auto_20180131_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finishincome',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
