# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModle', '0005_order_finishincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='paytime',
            field=models.DateTimeField(null=True),
        ),
    ]
